<a href="https://colab.research.google.com/github/pkrc267/IndoorLocalization/blob/master/Improved_Relaxed_Accuracy_13_04_2020.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
# import pandas.util.testing as tm
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import KMeans
from sklearn import datasets
from io import StringIO

from sklearn.tree import export_graphviz
from sklearn.model_selection import train_test_split
from sklearn import tree
from sklearn import metrics

In [0]:
frame0=pd.read_csv("/content/newRssiDblock-4.csv")

## Reading processed data without **'Z'** attribute

In [0]:
frame0.head()

        Name            Address  Signal Level  ...   Y              MAC  Location
0   BPGC-NAB  70:EA:1A:22:8F:E0           -41  ...  16  124150763130848      1016
1   BPGC-NAB  08:4F:A9:10:4B:80           -49  ...  16    9138231856000      1016
2   BPGC-NAB  00:A3:8E:60:F2:A0           -72  ...  16     702468387488      1016
3  BPGC-WIFI  40:01:7A:B1:00:40           -70  ...  16   70375097565248      1016
4   BPGC-NAB  70:EA:1A:22:A9:A0           -66  ...  16  124150763137440      1016

[5 rows x 7 columns]

## Performing **_One-Hot Encoding_** to create new features out of "*Categorical data*"

In [0]:
frame = pd.get_dummies(frame0)

In [0]:
frame.head()

   Signal Level   X  ...  Address_AC:E2:D3:B6:BA:1E  Address_BC:16:F5:9F:6E:F0
0           -41  10  ...                          0                          0
1           -49  10  ...                          0                          0
2           -72  10  ...                          0                          0
3           -70  10  ...                          0                          0
4           -66  10  ...                          0                          0

[5 rows x 70 columns]

### new features help in stronger prediction

In [0]:
from sklearn.ensemble import RandomForestClassifier

In [0]:
TV=frame.drop(['X','Y'], axis=1)
FV=frame.Location
TV.fillna(TV.mean, inplace=True)

Filled NaN entries with **mean** of corresponding columns

In [0]:
TV.head()

   Signal Level  ...  Address_BC:16:F5:9F:6E:F0
0           -41  ...                          0
1           -49  ...                          0
2           -72  ...                          0
3           -70  ...                          0
4           -66  ...                          0

[5 rows x 68 columns]

In [0]:
TV_train,TV_test,FV_train,FV_test=train_test_split(TV, FV, test_size=0.1, random_state=1)

## Actual Accuracy

In [0]:
clf = RandomForestClassifier(max_depth=8,random_state=0)
clf.fit(TV_train,FV_train)
FV_pred = clf.predict(TV_test)
print(clf.score(TV_test,FV_test)*100)

28.235294117647058

In [0]:
# FV_test.to_numpy()

In [0]:
original = pd.Series([],dtype='float64')
original['x'] = FV_test.to_numpy(copy=True)
original['y'] = FV_test.to_numpy(copy=True)
# original['z'] = FV_test

In [0]:
# original['x'].shape
# type(original)

In [0]:
v = FV_test.to_numpy(copy=True)

In [0]:
# v.size

In [0]:
# original['x']
# FV_test.size

In [0]:
for i in range(0, FV_test.size):
  # original['z'][i] = v[i] %100
  v[i] = v[i] // 100
  original['y'][i] = v[i] %100
  v[i] = v[i] // 100
  original['x'][i] = v[i] %100
  v[i] = v[i] // 100

In [0]:
# original['x'].shape

In [0]:
predicted = pd.Series([],dtype='float64')
predicted['x'] = FV_pred.copy()
predicted['y'] = FV_pred.copy()
# predicted['z'] = FV_pred

In [0]:
for i in range(0,FV_pred.size):
  # predicted['z'][i] = FV_pred[i] %100
  FV_pred[i] = FV_pred[i] // 100
  predicted['y'][i] = FV_pred[i] %100
  FV_pred[i] = FV_pred[i] // 100
  predicted['x'][i] = FV_pred[i] %100
  FV_pred[i] = FV_pred[i] // 100

In [0]:
# predicted['x'].shape

In [0]:
# type(original['x'])

In [0]:
def relaxaCheck(predicted, original):
  relaxed = original.copy()
  for i in range(0, predicted.size):
    if predicted[i] in range(original[i]-2, original[i]+2):
      relaxed[i] = 1
    else:
      relaxed[i] = 0
  
  return relaxed

In [0]:
relaxed_x = relaxaCheck(predicted['x'], original['x'])#.to_numpy())
relaxed_y = relaxaCheck(predicted['y'], original['y'])#.to_numpy())
# relaxed_z = relaxaCheck(predicted['z'], original['z'].to_numpy())

In [0]:
# relaxed_x

## Relaxed Accuracy

In [0]:
c=0
for i in range(0, relaxed_x.size):
  if relaxed_x[i] == relaxed_y[i] == 1: #relaxed_z[i] == 1:
    c+=1

print(100*c/relaxed_x.size)

80.0